{
 "title": "Heat Pump LuxWS",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperatures",
   "type": "gauge",
   "description": "FLOW: The flow temperature in degrees celsius. The flow temperature refers to the temperature of the water in the supply (flow) pipe in a heating system or separate part of a heating system.\n\nRETURN: The return temperature in degrees celsius. The return temperature is the temperature of the water in the pipe system after heat has been released into the building. The difference between inlet temperature and return temperature of the water occurs during transport through the heating system.\n\nTFL1: Temperaturfühler Flüssigkeit vor EEV Heizen (EEVH TFL1)\n\nTFL2: Temperaturfühler Flüssigkeit vor EEV Kühlen (EEVC TFL2)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "luxws_temperature{name=\"flow\"}",
     "legendFormat": "{{name}} (pipes)"
    },
    {
     "expr": "luxws_temperature{name=\"return\"}",
     "legendFormat": "Return (current)"
    },
    {
     "expr": "luxws_temperature{name=\"return target\"}",
     "legendFormat": "Return (target)"
    },
    {
     "expr": "luxws_temperature{name=\"hot gas\"}",
     "legendFormat": "Hot gas"
    },
    {
     "expr": "luxws_temperature{name=\"TFL1\"}",
     "legendFormat": "TF Heating"
    },
    {
     "expr": "luxws_temperature{name=\"TFL2\"}",
     "legendFormat": "TF Cooling"
    }
   ]
  },
  {
   "title": "Switch Offs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "luxws_latest_switchoff*1000 ", "legendFormat": "{{reason}}" }
   ]
  },
  {
   "title": "Outdoor Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "luxws_temperature{name=\"outdoor temp.\"}",
     "legendFormat": "Outdoor Temp"
    },
    {
     "expr": "luxws_temperature{name=\"outdoor temp. ø\"}",
     "legendFormat": "AVG Outdoor Temp"
    }
   ]
  },
  {
   "title": "Domestic Hot Water",
   "type": "stat",
   "description": "The actual service water temperature in degrees celsius. The current temperature of water supplying hot water taps.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "luxws_temperature{name=\"DHW\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "luxws_temperature{name=\"DHW target\"}",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Input (on/off)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "luxws_input{name=\"ASD\",unit=\"bool\"}",
     "legendFormat": "Abtauende, Soledruck, Durchfluss"
    },
    {
     "expr": "luxws_input{name=\"EVU\",unit=\"bool\"}",
     "legendFormat": "Energie-Vers. Sperre"
    },
    {
     "expr": "luxws_input{name=\"EVU 2\",unit=\"bool\"}",
     "legendFormat": "Energie-Vers. Sperre2"
    },
    {
     "expr": "luxws_input{name=\"HD\",unit=\"bool\"}",
     "legendFormat": "HochDruck"
    },
    {
     "expr": "luxws_input{name=\"MOT\",unit=\"bool\"}",
     "legendFormat": "Motorschutz"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "description": "FLOW: The flow temperature in degrees celsius. The flow temperature refers to the temperature of the water in the supply (flow) pipe in a heating system or separate part of a heating system.\n\nRETURN: The return temperature in degrees celsius. The return temperature is the temperature of the water in the pipe system after heat has been released into the building. The difference between inlet temperature and return temperature of the water occurs during transport through the heating system.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "luxws_temperature{name=\"flow\"}",
     "legendFormat": "{{name}} (pipes)"
    },
    {
     "expr": "luxws_temperature{name=\"return\"}",
     "legendFormat": "Return (current)"
    },
    {
     "expr": "luxws_temperature{name=\"return target\"}",
     "legendFormat": "Return (target)"
    },
    {
     "expr": "luxws_temperature{name=\"hot gas\"}",
     "legendFormat": "Hot gas"
    },
    {
     "expr": "luxws_temperature{name=\"DHW\"}",
     "legendFormat": "Domestic Hot Water"
    },
    {
     "expr": "luxws_temperature{name=\"suction compressor\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Outdoor Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "luxws_temperature{name=\"outdoor temp.\"}",
     "legendFormat": "Outdoor Temp"
    },
    {
     "expr": "luxws_temperature{name=\"outdoor temp. ø\"}",
     "legendFormat": "AVG Outdoor Temp"
    }
   ]
  },
  {
   "title": "Output (on/off)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "luxws_output{name=\"AV-defrost. valve\",unit=\"bool\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "luxws_output{name=\"BUP - DHW pump\",unit=\"bool\"}",
     "legendFormat": "Warmwasserumwälzpumpe"
    },
    {
     "expr": "luxws_output{name=\"HUP\",unit=\"bool\"}",
     "legendFormat": "Heizungsumwälzpumpe"
    },
    {
     "expr": "luxws_output{name=\"VBO\",unit=\"bool\"}",
     "legendFormat": "{{name}} Vorlauf"
    },
    {
     "expr": "luxws_output{name=\"VD1\",unit=\"bool\"}",
     "legendFormat": "Verdichter1"
    },
    {
     "expr": "luxws_output{name=\"ZIP\",unit=\"bool\"}",
     "legendFormat": "Zirkulationspumpe"
    },
    {
     "expr": "luxws_output{name=\"ZUP\",unit=\"bool\"}",
     "legendFormat": "Zusatzumwälzpumpe"
    },
    {
     "expr": "luxws_output{name=\"ZWE 1\",unit=\"bool\"}",
     "legendFormat": "Zweiter Wärmeerzeuger 1"
    },
    {
     "expr": "luxws_output{name=\"ZWE 2 - SST\",unit=\"bool\"}",
     "legendFormat": "Zweiter Wärmeerzeuger 2"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "luxws_output{name=\"rotation speed fan\"}",
     "legendFormat": "Fan Rotation"
    },
    {
     "expr": "luxws_output{name=\"freq. current\"}",
     "legendFormat": "Freq. Current"
    },
    {
     "expr": "luxws_output{name=\"freq. targ.value\"}",
     "legendFormat": "Freq. Target Value"
    }
   ]
  },
  {
   "title": "Operational Mode",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "luxws_operational_mode", "legendFormat": "{{mode}}" }
   ]
  },
  {
   "title": "HUP Heizungsumwälzpumpe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "luxws_output{name=\"HUP\", unit=\"pct\"}",
     "legendFormat": "HUP"
    }
   ]
  },
  {
   "title": "Flow Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "litreh" } },
   "targets": [
    {
     "expr": "luxws_input{name=\"flow rate\"}",
     "legendFormat": "Flow Rate l/h"
    }
   ]
  },
  {
   "title": "Druck BAR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "expr": "luxws_input{name=\"HD\", unit=\"bar\"}",
     "legendFormat": "Hochdruck HD"
    },
    {
     "expr": "luxws_input{name=\"ND\", unit=\"bar\"}",
     "legendFormat": "Niederdruck ND"
    }
   ]
  },
  {
   "title": "Supplied Heat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "rate(luxws_supplied_heat{name=\"total\"}[$interval]) /100",
     "legendFormat": "Supplied Heat Total"
    },
    {
     "expr": "rate(luxws_supplied_heat{name=\"heating\"}[$interval]) /100",
     "legendFormat": "Energy Input Total"
    }
   ]
  },
  {
   "title": "EEV Elektronisches Expansionsventil",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "luxws_output{name=\"EEV heating\"}",
     "legendFormat": "EEV Heating"
    },
    {
     "expr": "luxws_output{name=\"EEV cooling\"}",
     "legendFormat": "EEV Cooling"
    }
   ]
  },
  {
   "title": "Energy Input",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Δ kWh" } },
   "targets": [
    {
     "expr": "rate(luxws_energy_input{name=\"total\"}[$interval]) *1000",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(luxws_energy_input{name=\"heating\"}[$interval]) *1000",
     "legendFormat": "Heating"
    },
    {
     "expr": "rate(luxws_energy_input{name=\"domestic hot water\"}[$interval])*1000",
     "legendFormat": "Hot water"
    }
   ]
  },
  {
   "title": "Heating Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    { "expr": "luxws_heat_capacity", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Coefficient of Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "COP" } },
   "targets": [
    {
     "expr": "luxws_supplied_heat{name=\"total\"} / luxws_energy_input{name=\"total\"} ",
     "legendFormat": "COP"
    }
   ]
  }
 ]
}