{
 "title": "Heat Pump LuxWS",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperatures",
   "type": "stat",
   "description": "FLOW: The flow temperature in degrees celsius. The flow temperature refers to the temperature of the water in the supply (flow) pipe in a heating system or separate part of a heating system.\n\nRETURN: The return temperature in degrees celsius. The return temperature is the temperature of the water in the pipe system after heat has been released into the building. The difference between inlet temperature and return temperature of the water occurs during transport through the heating system.\n\nTFL1: Temperaturfühler Flüssigkeit vor EEV Heizen (EEVH TFL1)\n\nTFL2: Temperaturfühler Flüssigkeit vor EEV Kühlen (EEVC TFL2)",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "luxws_temperature{name=\"flow\"}",
     "legendFormat": "{{name}} (pipes)"
    },
    {
     "expr": "luxws_temperature{name=\"return\"}",
     "legendFormat": "Return (current)"
    },
    {
     "expr": "luxws_temperature{name=\"return target\"}",
     "legendFormat": "Return (target)"
    }
   ]
  },
  {
   "title": "Operational Mode",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "luxws_operational_mode_id", "legendFormat": "{{mode}}" }
   ]
  },
  {
   "title": "Coefficient of Performance (COP)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deriv(luxws_supplied_heat{name=\"total\"}[30m])  /  rate(luxws_energy_input{name=\"total\"}[30m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "stat",
   "description": "FLOW: The flow temperature in degrees celsius. The flow temperature refers to the temperature of the water in the supply (flow) pipe in a heating system or separate part of a heating system.\n\nRETURN: The return temperature in degrees celsius. The return temperature is the temperature of the water in the pipe system after heat has been released into the building. The difference between inlet temperature and return temperature of the water occurs during transport through the heating system.\n\nTFL1: Temperaturfühler Flüssigkeit vor EEV Heizen (EEVH TFL1)\n\nTFL2: Temperaturfühler Flüssigkeit vor EEV Kühlen (EEVC TFL2)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "luxws_temperature{name=\"hot gas\"}",
     "legendFormat": "Hot Gas"
    },
    {
     "expr": "luxws_temperature{name=\"TFL1\"}",
     "legendFormat": "TF Heating"
    },
    {
     "expr": "luxws_temperature{name=\"TFL2\"}",
     "legendFormat": "TF Cooling"
    },
    {
     "expr": "luxws_temperature{name=\"DHW\"}",
     "legendFormat": "Hot Water"
    },
    {
     "expr": "luxws_defrost{name=\"demand\",unit=\"pct\"}",
     "legendFormat": "Defrost Demand"
    }
   ]
  },
  {
   "title": "Switch Offs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "luxws_latest_switchoff*1000 ", "legendFormat": "{{reason}}" },
    {
     "expr": "luxws_defrost{name=\"last\",unit=\"ts\"}*1000 ",
     "legendFormat": "last defrost"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "luxws_latest_error*1000", "legendFormat": "{{reason}}" }
   ]
  },
  {
   "title": "Outdoor Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "luxws_temperature{name=\"outdoor temp.\"}",
     "legendFormat": "Outdoor Temp"
    },
    {
     "expr": "luxws_temperature{name=\"outdoor temp. ø\"}",
     "legendFormat": "AVG Outdoor Temp"
    }
   ]
  },
  {
   "title": "Domestic Hot Water",
   "type": "timeseries",
   "description": "The actual service water temperature in degrees celsius. The current temperature of water supplying hot water taps.",
   "gridPos": { "h": 12, "w": 22, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "luxws_temperature{name=\"DHW\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "luxws_temperature{name=\"DHW target\"}",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "description": "FLOW: The flow temperature in degrees celsius. The flow temperature refers to the temperature of the water in the supply (flow) pipe in a heating system or separate part of a heating system.\n\nRETURN: The return temperature in degrees celsius. The return temperature is the temperature of the water in the pipe system after heat has been released into the building. The difference between inlet temperature and return temperature of the water occurs during transport through the heating system.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "luxws_temperature{name=\"flow\"}",
     "legendFormat": "{{name}} (pipes)"
    },
    {
     "expr": "luxws_temperature{name=\"return\"}",
     "legendFormat": "Return (current)"
    },
    {
     "expr": "luxws_temperature{name=\"return target\"}",
     "legendFormat": "Return (target)"
    },
    {
     "expr": "luxws_temperature{name=\"hot gas\"}",
     "legendFormat": "Hot gas"
    },
    {
     "expr": "luxws_temperature{name=\"DHW\"}",
     "legendFormat": "Domestic Hot Water"
    },
    {
     "expr": "luxws_temperature{name=\"suction compressor\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "luxws_temperature{name=\"return\"} - ignoring(name) luxws_temperature{name=\"return target\"}",
     "legendFormat": "Flow-Return (ΔT)"
    },
    {
     "expr": "luxws_temperature{name=\"heat source inlet\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "luxws_temperature{name=\"max. flow temp.\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Input (on/off)",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "luxws_input{name=\"ASD\",unit=\"bool\"}",
     "legendFormat": "Abtauende, Soledruck, Durchfluss"
    },
    {
     "expr": "luxws_input{name=\"EVU\",unit=\"bool\"}",
     "legendFormat": "Energie-Vers. Sperre"
    },
    {
     "expr": "luxws_input{name=\"EVU 2\",unit=\"bool\"}",
     "legendFormat": "Energie-Vers. Sperre (Smart Grid)"
    },
    {
     "expr": "luxws_input{name=\"HD\",unit=\"bool\"}",
     "legendFormat": "HochDruck (Off=Ok)"
    },
    {
     "expr": "luxws_input{name=\"MOT\",unit=\"bool\"}",
     "legendFormat": "Motorschutz (On=OK)"
    },
    {
     "expr": "luxws_input{name=\"STL immersion heater\",unit=\"bool\"}",
     "legendFormat": "STL immers Heater"
    },
    {
     "expr": "luxws_input{name=\"SWT\",unit=\"bool\"}",
     "legendFormat": "SWT / PV"
    }
   ]
  },
  {
   "title": "Output (on/off)",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "luxws_output{name=\"AV-defrost. valve\",unit=\"bool\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "luxws_output{name=\"BUP - DHW pump\",unit=\"bool\"}",
     "legendFormat": "Warmwasserumwälzpumpe"
    },
    {
     "expr": "luxws_output{name=\"HUP\",unit=\"bool\"}",
     "legendFormat": "Heizungsumwälzpumpe"
    },
    {
     "expr": "luxws_output{name=\"VBO\",unit=\"bool\"}",
     "legendFormat": "{{name}} Vorlauf"
    },
    {
     "expr": "luxws_output{name=\"VD1\",unit=\"bool\"}",
     "legendFormat": "Verdichter1"
    },
    {
     "expr": "luxws_output{name=\"ZIP\",unit=\"bool\"}",
     "legendFormat": "Zirkulationspumpe"
    },
    {
     "expr": "luxws_output{name=\"ZUP\",unit=\"bool\"}",
     "legendFormat": "Zusatzumwälzpumpe"
    },
    {
     "expr": "luxws_output{name=\"ZWE 1\",unit=\"bool\"}",
     "legendFormat": "Zweiter Wärmeerzeuger 1"
    },
    {
     "expr": "luxws_output{name=\"ZWE 2 - SST\",unit=\"bool\"}",
     "legendFormat": "Zweiter Wärmeerzeuger 2"
    }
   ]
  },
  {
   "title": "Operational Mode",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "luxws_operational_mode", "legendFormat": "{{mode}}" }
   ]
  },
  {
   "title": "Outdoor Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "luxws_temperature{name=\"outdoor temp.\"}",
     "legendFormat": "Outdoor Temp"
    },
    {
     "expr": "luxws_temperature{name=\"outdoor temp. ø\"}",
     "legendFormat": "AVG Outdoor Temp"
    }
   ]
  },
  {
   "title": "Flow Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "litreh" } },
   "targets": [
    {
     "expr": "luxws_input{name=\"flow rate\"}",
     "legendFormat": "Flow Rate l/h"
    }
   ]
  },
  {
   "title": "HUP Heizungsumwälzpumpe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "luxws_output{name=\"HUP\", unit=\"pct\"}",
     "legendFormat": "HUP"
    }
   ]
  },
  {
   "title": "Supplied Heat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "Δ kWh" } },
   "targets": [
    {
     "expr": "deriv(luxws_supplied_heat{name=\"total\"}[15m]) * 15*60",
     "legendFormat": "Total"
    },
    {
     "expr": "deriv(luxws_supplied_heat{name=\"heating\"}[15m]) * 15*60",
     "legendFormat": "Heating"
    },
    {
     "expr": "deriv(luxws_supplied_heat{name=\"domestic hot water\"}[15m]) * 15*60",
     "legendFormat": "Hot Water"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "luxws_output{name=\"rotation speed fan\"}",
     "legendFormat": "Fan Rotation"
    },
    {
     "expr": "luxws_output{name=\"freq. current\"}",
     "legendFormat": "Freq. Current"
    },
    {
     "expr": "luxws_output{name=\"freq. targ.value\"}",
     "legendFormat": "Freq. Target Value"
    }
   ]
  },
  {
   "title": "Energy Input",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "Δ kWh" } },
   "targets": [
    {
     "expr": "rate(luxws_energy_input{name=\"total\"}[1h]) *1000",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(luxws_energy_input{name=\"heating\"}[1h]) *1000",
     "legendFormat": "Heating"
    },
    {
     "expr": "rate(luxws_energy_input{name=\"domestic hot water\"}[1h])*1000",
     "legendFormat": "Hot water"
    }
   ]
  },
  {
   "title": "Druck BAR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "expr": "luxws_input{name=\"HD\", unit=\"bar\"}",
     "legendFormat": "Hochdruck HD"
    },
    {
     "expr": "luxws_input{name=\"ND\", unit=\"bar\"}",
     "legendFormat": "Niederdruck ND"
    }
   ]
  },
  {
   "title": "Coefficient of Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "COP" } },
   "targets": [
    {
     "expr": "deriv(luxws_supplied_heat{name=\"total\"}[30m])  /  rate(luxws_energy_input{name=\"total\"}[30m])",
     "legendFormat": "COP"
    }
   ]
  },
  {
   "title": "EEV Elektronisches Expansionsventil",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "luxws_output{name=\"EEV heating\"}",
     "legendFormat": "EEV Heating"
    },
    {
     "expr": "luxws_output{name=\"EEV cooling\"}",
     "legendFormat": "EEV Cooling"
    }
   ]
  },
  {
   "title": "Heating Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    { "expr": "luxws_heat_capacity", "legendFormat": "Heat Capacity" }
   ]
  },
  {
   "title": "Elapsed Times / Duration",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "luxws_elapsed_duration_seconds{name=\"SCB time\"}/60\n",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "luxws_elapsed_duration_seconds{name=\"CP off since\"}/60",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "luxws_elapsed_duration_seconds{name=\"HP since\"}/60",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "luxws_elapsed_duration_seconds{name=\"TDI since\"}/60",
     "legendFormat": "Thermische Desinfektion"
    },
    {
     "expr": "luxws_elapsed_duration_seconds{name=\"blockade DHW\"}/60",
     "legendFormat": "Blockade DHW"
    },
    {
     "expr": "luxws_elapsed_duration_seconds{name=\"ZWE1 since\"}/60",
     "legendFormat": "Zweiter Waermeerzeuger 1."
    },
    {
     "expr": "luxws_elapsed_duration_seconds{name=\"ZWE2 since\"}/60",
     "legendFormat": "Zweiter Waermeerzeuger 2."
    },
    {
     "expr": "luxws_elapsed_duration_seconds{name=\"amount PV\"}/60",
     "legendFormat": "PV"
    }
   ]
  },
  {
   "title": "operating hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "luxws_operating_duration_seconds{name=\"operating hours ZWE1\"}/60/60",
     "legendFormat": "ZWE 1"
    },
    {
     "expr": "luxws_operating_duration_seconds{name=\"operating hours ZWE2\"}/60/60",
     "legendFormat": "ZWE 2"
    }
   ]
  },
  {
   "title": "Defrost Demand",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "luxws_defrost{name=\"demand\"}",
     "legendFormat": "Defrost demand"
    }
   ]
  },
  {
   "title": "Domestic Hot Water Temperature Changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "deriv(luxws_temperature{name=\"DHW\"}[15m]) * 15 *60",
     "legendFormat": "Hotwater ΔC"
    }
   ]
  }
 ]
}